<div id="footer">
    <div id="footer-menu">
        <ul>    
            <li><a href="<?php echo $this->url(array(
                        'controller' => 'orrialdeak',
                        'action' => 'ikusi',
                        'orria' => 'zer_da_hau'
                    ),'',true);?>"><?php echo $this->translate('Zer da hau?')?></a></li>
            <li><a href="<?php echo $this->url(array(
                'controller' => 'lekuak',
                'action' => 'bilatu'
            ),'',true); ?>"><?php echo $this->translate('Lekuak'); ?></a></li>
            <li><a href="<?php echo $this->url(array(
                'controller' => 'kontaktua'
            ), '', true);?>"><?php echo $this->translate('Kontaktua'); ?></a></li>
            <li><a href="<?php echo $this->url(array(
                        'controller' => 'orrialdeak',
                        'action' => 'ikusi',
                        'orria' => 'honi_buruz'
                    ),'',true);?>"><?php echo $this->translate('Honi Buruz')?></a></li></div>
        </ul>
    <div id="copy">Copyright &copy; 2012 Mintzatu</div>
    <div id="kontadorea"><?php echo $this->Kontadorea(); ?></div>
</div><!-- #footer -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30217319-1']);
  _gaq.push(['_setDomainName', 'mintzatu.com']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- <div id="fb-root"></div> -->
<!-- <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=277804258962107";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> -->