<h1><?php echo $this->translate('Lekuen Bilaketa'); ?></h1>
<a href="<?php echo $this->url(array(
        'controller' => 'lekuak',
        'action' => 'berria'
    ),'', true);?>"><img src="<?php echo $this->baseUrl('/img/berria.png'); ?>" alt="Berria Sortu" title="Leku Berria Sortu" class="tooltiped" id="lekuIrudia"/></a>

<form id="lekuBilaketa" action="<?php echo $this->url(array(
    'controller' => 'lekuak',
    'action' => 'bilatu'
),'',true);?>" method="get">
    <label for="lekuak"></label>
    <input type="text" name="lekuak" class="" id="lekuak" value="<?php echo ($this->bilaketa)? $this->bilaketa : $this->translate('lekuak bilatu') ; ?>">
    <select name="kat" id="kat">
        <option value="0" label="Denak"><?php echo $this->translate('Denak'); ?></option>
    <?php foreach ($this->kategoriak as $id => $izena) : ?>
        <option value="<?php echo $id; ?>" label="<?php echo $izena; ?>" <?php echo ($this->kat == $id)? 'selected':''; ?>><?php echo $izena; ?></option>
    <?php endforeach;?>
    </select>
    <input type="image" class="lupa" src="<?php echo $this->baseUrl('/img/lupa.png');?>" /> 

</form>
<?php if ($this->result) : ?>
<div class="list-box">
    <h2>Emaitzak</h2>
    <ul>
        <?php foreach ($this->result as $lekua) : ?>
        <li>
            <ul>
            <li class="pic"><?php echo $this->KategoriaIrudia($lekua, 'aktibitatea', true); ?></li>
            <li class="what"><?php echo '<span id="izena"><a href="'.$this->url(array(
                'controller' => 'lekuak',
                'action' => 'ikusi',
                'lekua' => $lekua->getUrl()
            ),'', true).'">'.$lekua->getIzena().'</a></span>'; ?>
            <span class="herria"> - <?php echo $lekua->getHerria();?></span><br />
            <span clasS="kategoria"><?php echo $lekua->getKategoriak()->getIzena(); ?></span>
            <?php if ($lekua->getDistantzia()): ?><span clasS="kategoria"><?php echo $lekua->getDistantzia(); ?> km</span> <?php endif;?>
            </li>
            <li class="when">
            <?php 
                $count = sizeof($lekua->getChecks());
                if ($count>0):
            ?>
            <span class="checksCounter"><?php echo $count; ?> pertsona egon dira</span>
            <?php else:  ?>
            <span class="checksCounter"></span>
            <?php endif; ?>
            
            </li>
            </ul>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php if ($this->botoia) :?>
        <p><a class="link-button" href="<?php echo $this->url(array(
            'controller' => 'lekuak',
            'action' => 'berria'
        ),'', true);?>"><?php echo $this->translate('Berria Sortu'); ?></a></p>
    <?php endif; ?>
</div>
<?php else: ?>
<div class="list-box">
    <h2>Emaitzak</h2>
    <p><?php echo $this->translate('Ez da lekurik aurkitu. Kategori hontako lekuren bat ezagutu eskero, sortu ezazu besteek ere ezagutu dezaten.'); ?><br />
    <a class="link-button" href="<?php echo $this->url(array(
        'controller' => 'lekuak',
        'action' => 'berria'
    ),'', true);?>"><?php echo $this->translate('Berria Sortu'); ?></a></p>
</div>

<?php endif; ?>