<?php if ($this->mezua) : ?>
<div id="dialog-mezua">
    <?php echo $this->mezua; ?>
</div>
<?php endif;?>
<h1><?php echo $this->translate('Kontaktua'); ?></h1>
<p><?php echo $this->translate('Bete ezazu hurrengo formulakia gurekin harremanetan jartzeko, edozein gairi buruz idatzi gaitzakezu.')?></p>
<div class="form-box">
    <h2><?php echo $this->translate('Kontakturako Formulakia')?></h2>
    <?php echo $this->form;?>
</div>